name: CI Test and Notify

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Dependent Services
        run: docker-compose -f test/docker-compose.yml up -d
        working-directory: workflow-parser

      - name: Install Dependencies
        run: yarn install
        working-directory: workflow-parser

      - name: Run Jest Tests
        run: yarn test
        working-directory: workflow-parser
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Stop Services
        if: always()
        run: docker-compose -f test/docker-compose.yml down
        working-directory: workflow-parser

      - name: Notify Slack of Job Status
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C08D8UKMQVD"
          slack-message: |
            {
              "text": "*CI Test and Notify* completed with status: '${{ job.status }}'"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
